model:
  target: Models.gaussian_diffusion.Diffusion_TS
  params:
    net: S4
    seq_len: 36
    pred_len: 36
    n_node: 10000
    n_layer_enc: 3
    n_layer_dec: 3
    d_model: 128  # 4 X 16
    timesteps: 500
    sampling_timesteps: 500
    loss_type: 'l1'
    beta_schedule: 'cosine'
    n_heads: 4
    mlp_hidden_times: 4
    attn_pd: 0.0
    resid_pd: 0.0
    kernel_size: 1
    padding_size: 0

solver:
  base_lr: 1.0e-5
  max_epochs: 18000
  results_folder: ./Checkpoints-Internet ############## change this
  gradient_accumulate_every: 2
  save_cycle: 1800  # max_epochs // 10
  ema:
    decay: 0.995
    update_interval: 10
  
  scheduler:
    target: engine.lr_sch.ReduceLROnPlateauWithWarmup
    params:
      factor: 0.5
      patience: 4000
      min_lr: 1.0e-5
      threshold: 1.0e-1
      threshold_mode: rel
      warmup_lr: 8.0e-4
      warmup: 500 
      verbose: False

dataloader:
  train_dataset:
    target: Utils.Data_utils.real_datasets.CustomDataset
    params:
      name: Internet  ############## change this
      proportion: -1  # Set to rate < 1 if training conditional generation
      data_root: /home/user/daojun/Data/TS_Traffic/Milano/trainval.npy
      seq_len: 36  # seq_length
      pred_len: 36
      save2npy: True
      neg_one_to_one: True
      seed: 123
      period: train

  test_dataset:
    target: Utils.Data_utils.real_datasets.CustomDataset
    params:
      name: Internet ############## change this
      proportion: -1  # rate
      data_root: /home/user/daojun/Data/TS_Traffic/Milano/test.npy
      seq_len: 36
      pred_len: 36  # seq_length 24, 36, 48, 72
      save2npy: True
      neg_one_to_one: True
      seed: 123
      period: test
      style: separate
      distribution: geometric
    coefficient: 1.0e-2
    step_size: 5.0e-2
    sampling_steps: 200

  batch_size: 128
  sample_size: 256
  shuffle: True